// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZKETU0-JimcNownScU4-bpV-JbCiRV4',
    appId: '1:274815419118:web:67c8c63efed52d640469ff',
    messagingSenderId: '274815419118',
    projectId: 'fir-notes-b0c64',
    authDomain: 'fir-notes-b0c64.firebaseapp.com',
    storageBucket: 'fir-notes-b0c64.firebasestorage.app',
    measurementId: 'G-1Y003CKCJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAypSIaHGyXzW99OaNJzs3XpiCHov-cSAI',
    appId: '1:274815419118:android:435e0c45b459e92a0469ff',
    messagingSenderId: '274815419118',
    projectId: 'fir-notes-b0c64',
    storageBucket: 'fir-notes-b0c64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpFc0s84L9rY8F7TWVBhp3saNsMSiAL7k',
    appId: '1:274815419118:ios:f9c8155ab0af252b0469ff',
    messagingSenderId: '274815419118',
    projectId: 'fir-notes-b0c64',
    storageBucket: 'fir-notes-b0c64.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpFc0s84L9rY8F7TWVBhp3saNsMSiAL7k',
    appId: '1:274815419118:ios:f9c8155ab0af252b0469ff',
    messagingSenderId: '274815419118',
    projectId: 'fir-notes-b0c64',
    storageBucket: 'fir-notes-b0c64.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLZKETU0-JimcNownScU4-bpV-JbCiRV4',
    appId: '1:274815419118:web:e81004a690f351350469ff',
    messagingSenderId: '274815419118',
    projectId: 'fir-notes-b0c64',
    authDomain: 'fir-notes-b0c64.firebaseapp.com',
    storageBucket: 'fir-notes-b0c64.firebasestorage.app',
    measurementId: 'G-S12SZD7NGH',
  );
}
